from django.urls import path
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

from .views import (
    ChangePasswordView,
    ClearAdminSessionView,
    LibraryLoginView,
    LogoutView,
    MeView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    RegisterView,
    UserListView,
    UserRoleUpdateView,
)

urlpatterns = [
    path(
        "register/", 
        RegisterView.as_view(), 
        name="register"
    ),
    path(
        "login/",
        LibraryLoginView.as_view(),
        name="login",
    ),
    path(
        "clear-admin-session/",
        ClearAdminSessionView.as_view(),
        name="clear-admin-session",
    ),
    path(
        "logout/",
         LogoutView.as_view(),
          name="logout"
    ),
    path(
        "refresh/", 
        TokenRefreshView.as_view(), 
        name="token-refresh"
    ),
    path(
        "me/", 
        MeView.as_view(), 
        name="me"
    ),
    path(
        "password-reset/",
        PasswordResetRequestView.as_view(),
        name="password-reset",
    ),
    path(
        "password-reset/confirm/",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "change-password/",
        ChangePasswordView.as_view(),
        name="change-password",
    ),
    path(
        "users/",
        UserListView.as_view(),
        name="user-list",
    ),
    path(
        "users/<int:pk>/role/",
        UserRoleUpdateView.as_view(),
        name="user-role-update",
    ),
]