# Generated by Django 4.2.30 on 2026-07-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_book_id_f6c98f_idx',
            old_name='reviews_rev_book_id_9d6b3e_idx',
        ),
    ]
