# Generated by Django 4.2.30 on 2026-07-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DUE_SOON_REMINDER', 'Due in 2 Days'), ('DUE_TODAY_REMINDER', 'Due Today'), ('RESERVATION_AVAILABLE', 'Reservation Available'), ('FINE_ISSUED', 'Fine Issued')], max_length=50),
        ),
    ]
