# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DUE_SOON_REMINDER', 'Due in 2 Days'), ('DUE_TODAY_REMINDER', 'Due Today'), ('RESERVATION_AVAILABLE', 'Reservation Available'), ('FINE_ISSUED', 'Fine Issued'), ('FINE_PAID', 'Fine Paid')], max_length=50),
        ),
    ]
